---
- hosts: all

  tasks:
    - name: Install apche
      apt: name=apache2 state=present
    - name: create index.html
      file: dest=/var/www/html/index.html state=touch
    - name: Add content in index.html
      copy: dest=/var/www/html/index.html content='This is test page create by anible'
    - name: start apache service
      service: name=apache2 state=started
